version: "3"

services:
    rabbitmq:
        image: rabbitmq:3-management
        hostname: "rabbitmq"
        ports:
            - "15672:15672"
            - "5672:5672"
    producer:
        build: 
            context: producer
    consumer_all:
        build: 
            context: consumer_all
    consumer_critical:
        build: 
            context: consumer_critical
