# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: storage.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'storage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstorage.proto\x12\x07storage\x1a\x1fgoogle/protobuf/timestamp.proto\"\\\n\x05Value\x12\x0f\n\x07payload\x18\x01 \x01(\x04\x12\x33\n\nupdated_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x00\x88\x01\x01\x42\r\n\x0b_updated_at\"+\n\nPutRequest\x12\x1d\n\x05value\x18\x01 \x01(\x0b\x32\x0e.storage.Value\"\x1c\n\x0bPutResponse\x12\r\n\x05value\x18\x01 \x01(\x04\"\x0c\n\nGetRequest\",\n\x0bGetResponse\x12\x1d\n\x05value\x18\x01 \x01(\x0b\x32\x0e.storage.Value2w\n\x07Storage\x12\x35\n\x08PutValue\x12\x13.storage.PutRequest\x1a\x14.storage.PutResponse\x12\x35\n\x08GetValue\x12\x13.storage.GetRequest\x1a\x14.storage.GetResponseB\x14Z\x12hsegrpc/;storagepbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'storage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\022hsegrpc/;storagepb'
  _globals['_VALUE']._serialized_start=59
  _globals['_VALUE']._serialized_end=151
  _globals['_PUTREQUEST']._serialized_start=153
  _globals['_PUTREQUEST']._serialized_end=196
  _globals['_PUTRESPONSE']._serialized_start=198
  _globals['_PUTRESPONSE']._serialized_end=226
  _globals['_GETREQUEST']._serialized_start=228
  _globals['_GETREQUEST']._serialized_end=240
  _globals['_GETRESPONSE']._serialized_start=242
  _globals['_GETRESPONSE']._serialized_end=286
  _globals['_STORAGE']._serialized_start=288
  _globals['_STORAGE']._serialized_end=407
# @@protoc_insertion_point(module_scope)
