[package]
name = "gossip"
version = "0.1.0"
edition = "2021"

[dependencies]
anysystem = "0.1.0"
clap = { version = "3.1.17", features = ["cargo", "derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sugars = "3"
